---
- name: Install Kubernetes components
  hosts: masters, workers
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: [apt-transport-https, ca-certificates, curl, gpg]
        state: present

    - name: Create directory for apt key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Kubernetes GPG key
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'

    - name: Install K8s tools
      apt:
        name: [kubelet, kubeadm, kubectl]
        state: present
        update_cache: yes

    - name: Hold K8s tools (prevent auto-upgrade)
      shell: apt-mark hold kubelet kubeadm kubectl