---
- name: Prepare nodes for Kubernetes
  hosts: masters, workers
  become: yes
  tasks:
    - name: Disable SWAP immediately
      command: swapoff -a
      changed_when: false  # Команда выполняется всегда, но статус changed нам тут не нужен

    - name: Remove SWAP from /etc/fstab permanently
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+.*)$'
        replace: '# \1'

    # Модули ядра и sysctl уже созданы Паккером, но эти таски проверяют их статус на лету
    - name: Ensure kernel modules are loaded
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Ensure sysctl parameters are applied
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
        state: present
        reload: yes
      loop:
        - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
        - { key: 'net.ipv4.ip_forward', value: '1' }
        - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }

    # Containerd